// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFkCPMQTuncaPLGDGawSLQ7wOpf9W4XFU',
    appId: '1:869324862424:web:782c4c3a43922fdaac38ad',
    messagingSenderId: '869324862424',
    projectId: 'project3-ac902',
    authDomain: 'project3-ac902.firebaseapp.com',
    storageBucket: 'project3-ac902.firebasestorage.app',
    measurementId: 'G-BJH1QE3XFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa3ZV3aPINob1LQ3_-JVe7FysTHalwU3w',
    appId: '1:869324862424:android:d128addb261c2152ac38ad',
    messagingSenderId: '869324862424',
    projectId: 'project3-ac902',
    storageBucket: 'project3-ac902.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlaN3269333Sv2xzGslsmcnBdyxFK1rW8',
    appId: '1:869324862424:ios:64a75796da88dc64ac38ad',
    messagingSenderId: '869324862424',
    projectId: 'project3-ac902',
    storageBucket: 'project3-ac902.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication03',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlaN3269333Sv2xzGslsmcnBdyxFK1rW8',
    appId: '1:869324862424:ios:64a75796da88dc64ac38ad',
    messagingSenderId: '869324862424',
    projectId: 'project3-ac902',
    storageBucket: 'project3-ac902.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication03',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFkCPMQTuncaPLGDGawSLQ7wOpf9W4XFU',
    appId: '1:869324862424:web:ed2999a29c66e2c5ac38ad',
    messagingSenderId: '869324862424',
    projectId: 'project3-ac902',
    authDomain: 'project3-ac902.firebaseapp.com',
    storageBucket: 'project3-ac902.firebasestorage.app',
    measurementId: 'G-QDLE06PBRL',
  );
}
